# Generated by Django 5.1.3 on 2026-08-12 10:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='webhook_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='webhook_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='webhook_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('retrying', 'Retrying'), ('success', 'Success'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['owner', '-created_at'], name='tasks_task_owner_i_35cb9a_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('owner', 'idempotency_key'), name='unique_task_idempotency_key_per_owner'),
        ),
    ]
