# Generated by Django 5.1.3 on 2026-08-12 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_idempotency_key_task_webhook_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_api_key', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='tasks.task')),
            ],
        ),
    ]
