# Generated by Django 5.1.3 on 2026-08-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskcredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcredential',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
